credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$abCDefghIjklmnopqrstuv"
cookie:
  name: pmj_cookie
  key: "my_super_secret_key"
  expiry_days: 30
