credentials:
  usernames:
    admin:
      email: "admin@example.com"
      name: "Admin"
      password: "$2b$12$...."
cookie:
  name: "pmj_app"
  key: "some_random_string"
  expiry_days: 30
